In [29]:
marks = [20, 30, 40, 40, 50, 60, 70, 90]
marks

[20, 30, 40, 40, 50, 60, 70, 90]

In [30]:
np.percentile(marks,25)

np.float64(37.5)

In [21]:
import pandas as pd
import numpy as np
from statistics import mode

In [9]:
# Question 1: Mean calculate karo.
mean = np.mean(marks)
print("Mean value =",mean)

Mean value = 50.0

In [10]:
# Question 2: Median calculate karo.
median = np.median(marks)
print("Median value =",median)

Median value = 45.0

In [ ]:
# Question 3: Mode find karo.

marks = [20, 30, 40, 40, 50, 60, 70, 90]
print(mode(marks))

40

In [23]:
# Question 4: Maximum aur minimum marks find karo.
max = np.max(marks)
print("Maximum value = ",max)

min = np.min(marks)
print("Minimum value = ",min)

Maximum value =  90
Minimum value =  20

In [24]:
# Question 5: Range calculate karo.
range = max - min
print("Range =",range)

Range = 70

In [25]:
# Question 6: Python mein standard deviation calculate karo.
std = np.std(marks)
print("STD=",std)

STD= 21.213203435596427

In [11]:
import pandas as pd
import numpy as np
from statistics import mode

df = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "Age": [18, 20, 19, 21, 22, 20, 19, 23, 21, 20],
    "Marks": [45, 60, 75, 80, 90, 60, 55, 95, 70, 70],
    "Study_Hours": [2, 4, 5, 6, 8, 3, 2, 9, 5, 6],
    "Attendance": [70, 80, 85, 90, 95, 75, 65, 98, 88, 82]
})

df

  Student  Age  Marks  Study_Hours  Attendance
0       A   18     45            2          70
1       B   20     60            4          80
2       C   19     75            5          85
3       D   21     80            6          90
4       E   22     90            8          95
5       F   20     60            3          75
6       G   19     55            2          65
7       H   23     95            9          98
8       I   21     70            5          88
9       J   20     70            6          82

In [4]:
# Q1. Calculate the mean of the Marks column.
print("Mean =",df["Marks"].mean())

Mean = 70.0

In [5]:
# Q2. Find the median of the Age column.
print("Median=",df["Marks"].median())

Median= 70.0

In [16]:
# Q3. Find the mode of the Marks column.
print(df["Marks"].mode())

0    60
1    70
Name: Marks, dtype: int64

In [17]:
# Q4. Find the maximum and minimum values of Study_Hours.
print("Maximum Hour=",df["Study_Hours"].max())
print("Minimum Hour=",df["Study_Hours"].min())

Maximum Hour= 9
Minimum Hour= 2

In [22]:
# Q5. Calculate the range of Marks.
max = df["Marks"].max()
max

min = df["Marks"].min()
min

range = max - min
print("Range =",range)

Range = 50

In [23]:
# Q6. Calculate the standard deviation of Marks using Pandas.
print("STD=",df["Marks"].std())

STD= 15.634719199411432

In [24]:
# Q7. Calculate the variance of Marks using Pandas.
print("Variance =",df["Marks"].var())

Variance = 244.44444444444446

In [25]:
# Q8. Find the total marks of all students.
print("Total marks=",df["Marks"].sum())

Total marks= 700

In [26]:
# Q9. Count how many students have marks greater than 70.
df[df["Marks"]>70]

  Student  Age  Marks  Study_Hours  Attendance
2       C   19     75            5          85
3       D   21     80            6          90
4       E   22     90            8          95
7       H   23     95            9          98

In [27]:
# Q10. Find the average attendance of all students.
print("Average Attendance =",df["Attendance"].mean())

Average Attendance = 82.8

In [33]:
# Q11. Calculate the 25th percentile of Marks.
print("25th percentile =",df["Marks"].quantile(0.25))

25th percentile = 60.0

In [34]:
# Q12. Calculate the 75th percentile of Marks.
print("75th percentile =",df["Marks"].quantile(0.75))

75th percentile = 78.75

In [39]:
# Q13. Find the first quartile (Q1) and third quartile (Q3) of Marks.

Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)

print(Q1)
print(Q3)

60.0
78.75

In [40]:
# Q14. Calculate the Interquartile Range (IQR).
IQR =  Q3-Q1
print(IQR)

18.75