In [113]:
# Part 1 — Data Inspection
# 1. Import Pandas and NumPy libraries.
# 2. Load the CSV file into a DataFrame named df.

import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\Hp\OneDrive\Desktop\Advance python\student_performance_dataset.csv")
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,unknown,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,unknown,not recorded,NaN
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,Unknown,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [114]:
# 3. Display the first 10 and last 5 rows.
print(df.head(10))
print(df.tail(5))

  Student_ID  Student Name   Gender Class           Subject Attendance_%  \
0       S075   Rohit Joshi     MALE   NaN           SCIENCE           81
1       S002    Neha Patel       m   10th           English          105
2       S092  Aarav Sharma  Unknown    12  Computer Science           95
3       S021  Pooja Kumari       f     XI  Computer Science           76
4       S092   Vikas Yadav     Male  12th  Computer Science          NaN
5       S002  Pooja Kumari       m   10th             Maths           62
6       S062   Anjali Jain     MALE    12       Mathematics          NaN
7       S026  Isha Agarwal       f    Ten          Computer          105
8       S088     Arjun Rao   Female   Ten           english          NaN
9       S103  Aarav Sharma       m   10th              math           95

  Study_Hours_Per_Day Exam_Score      City Parent_Contacted     Exam_Date  \
0             unknown         95       NaN              YES           NaN
1                 3.5         80   Jodhpur          unknown  not recorded
2                2.5         74   Jodhpur                no    2026-13-40
3                   0         95       NaN              Yes    15/09/2026
4                   0         72   jaipur               NaN  not recorded
5                 3.5         80   jaipur                 N    2026-13-40
6               three         72  Jodhpur                no    2026-13-40
7                 3.5        101   Unknown              Yes  not recorded
8                   6         88   Unknown              NaN    2026/09/15
9                2.5         101  Jodhpur                No    2026-09-15

           Remarks
0            good
1              NaN
2           Absent
3            good
4              NaN
5                -
6        Excellent
7  late submission
8           Absent
9              NaN
    Student_ID  Student Name   Gender Class           Subject Attendance_%  \
118       S042   Vikas Yadav      NaN   NaN             Maths           95
119       S044   Priya Singh        F  10th           English           88
120       S092  Aarav Sharma  Unknown    12  Computer Science           95
121       S088     Arjun Rao   Female   Ten           english          NaN
122       S062     Arjun Rao      NaN  10th           english           -5

    Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
118                 NaN        74    Unknown              Yes  2026/09/15
119               three         95     Delhi              YES  2026/09/15
120                2.5         74   Jodhpur                no  2026-13-40
121                   6         88   Unknown              NaN  2026/09/15
122                   6        74      sikar                Y  2026-09-15

    Remarks
118  Absent
119    Good
120  Absent
121  Absent
122  Absent

In [115]:
# 4. Find the total number of rows and columns.
print(df.shape)

(123, 12)

In [116]:
# 5. Display all column names and their data types.
print(df.dtypes)

Student_ID             object
Student Name           object
Gender                 object
Class                  object
Subject                object
Attendance_%           object
Study_Hours_Per_Day    object
Exam_Score             object
City                   object
Parent_Contacted       object
Exam_Date              object
Remarks                object
dtype: object

In [117]:
# 6. Check the DataFrame information using info() and summary statistics using describe().
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           123 non-null    object
 1   Student Name         123 non-null    object
 2   Gender               115 non-null    object
 3   Class                117 non-null    object
 4   Subject              115 non-null    object
 5   Attendance_%         99 non-null     object
 6   Study_Hours_Per_Day  113 non-null    object
 7   Exam_Score           115 non-null    object
 8   City                 113 non-null    object
 9   Parent_Contacted     107 non-null    object
 10  Exam_Date            102 non-null    object
 11  Remarks              93 non-null     object
dtypes: object(12)
memory usage: 11.7+ KB
None

In [118]:
print(df.describe(include ="all"))

       Student_ID  Student Name   Gender Class Subject Attendance_%  \
count         123           123      115   117     115           99
unique         74            15        9     9       9           10
top          S092  Aarav Sharma  Unknown  10th   Maths          105
freq            6            11       20    19      21           14

       Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
count                  113        115       113              107         102
unique                  11         11         9                7           5
top                     -2         88  Jodhpur               Yes  2026-13-40
freq                    15         16        21               22          27

       Remarks
count       93
unique       7
top      good
freq        19

In [119]:
# Part 2 — Data Quality Check
# 1. Count missing values in each column.
print(df.isnull().sum())

Student_ID              0
Student Name            0
Gender                  8
Class                   6
Subject                 8
Attendance_%           24
Study_Hours_Per_Day    10
Exam_Score              8
City                   10
Parent_Contacted       16
Exam_Date              21
Remarks                30
dtype: int64

In [120]:
# 2. Calculate the percentage of missing values in each column.
print(df.isnull().mean()*100)

Student_ID              0.000000
Student Name            0.000000
Gender                  6.504065
Class                   4.878049
Subject                 6.504065
Attendance_%           19.512195
Study_Hours_Per_Day     8.130081
Exam_Score              6.504065
City                    8.130081
Parent_Contacted       13.008130
Exam_Date              17.073171
Remarks                24.390244
dtype: float64

In [121]:
# 3. Count the exact duplicate rows.
print(df.duplicated().sum())

3

In [122]:
# 4. Display all duplicate rows without deleting them.
print(df[df.duplicated(keep=False)])

    Student_ID  Student Name   Gender Class           Subject Attendance_%  \
2         S092  Aarav Sharma  Unknown    12  Computer Science           95
8         S088     Arjun Rao   Female   Ten           english          NaN
15        S062     Arjun Rao      NaN  10th           english           -5
120       S092  Aarav Sharma  Unknown    12  Computer Science           95
121       S088     Arjun Rao   Female   Ten           english          NaN
122       S062     Arjun Rao      NaN  10th           english           -5

    Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
2                  2.5         74   Jodhpur                no  2026-13-40
8                     6         88   Unknown              NaN  2026/09/15
15                    6        74      sikar                Y  2026-09-15
120                2.5         74   Jodhpur                no  2026-13-40
121                   6         88   Unknown              NaN  2026/09/15
122                   6        74      sikar                Y  2026-09-15

    Remarks
2    Absent
8    Absent
15   Absent
120  Absent
121  Absent
122  Absent

In [123]:
# 5. Find the number of unique values in every column.
print(df.nunique())

Student_ID             74
Student Name           15
Gender                  9
Class                   9
Subject                 9
Attendance_%           10
Study_Hours_Per_Day    11
Exam_Score             11
City                    9
Parent_Contacted        7
Exam_Date               5
Remarks                 7
dtype: int64

In [124]:
# 6. Display unique values of Gender, Class, Subject and City.
print(df["Gender"].unique())
print(df["Class"].unique())
print(df["Subject"].unique())
print(df["City"].unique())

['MALE' ' m ' 'Unknown' ' f ' 'Male' 'Female' 'female' nan 'F' 'M']
[nan '10th' '12' 'XI' '12th' 'Ten' 'Class 10' '11' 'Class 12' '10']
['SCIENCE' 'English' 'Computer Science' 'Maths' 'Mathematics' 'Computer'
 'english' 'math' 'Science' nan]
[nan 'Jodhpur' 'Jodhpur ' ' jaipur ' 'Unknown' 'Delhi' 'sikar' 'Sikar'
 'Jaipur' 'SIKAR']

In [125]:
# 7. Identify columns containing inconsistent text values or invalid data.
for col in ["Gender", "Class", "Subject", "City","Student Name"]:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Gender:
Gender
Unknown    20
 m         17
Female     14
MALE       13
M          13
F          12
 f         10
female     10
NaN         8
Male        6
Name: count, dtype: int64

Class:
Class
10th        19
12          15
10          15
11          14
Class 10    13
Ten         12
12th        11
XI           9
Class 12     9
NaN          6
Name: count, dtype: int64

Subject:
Subject
Maths               21
math                14
SCIENCE             13
english             13
Science             13
Computer Science    12
Mathematics         12
Computer            10
NaN                  8
English              7
Name: count, dtype: int64

City:
City
Jodhpur     21
Unknown     19
SIKAR       17
Delhi       14
sikar       11
NaN         10
 jaipur     10
Sikar        9
Jaipur       9
Jodhpur      3
Name: count, dtype: int64

Student Name:
Student Name
Aarav Sharma    11
Karan Das       11
Rohit Joshi     10
Neha Patel      10
Isha Agarwal    10
Arjun Rao       10
Vikas Yadav      9
Mohit Saini      9
Rahul Verma      8
Pooja Kumari     7
Anjali Jain      7
Priya Singh      6
Sneha Gupta      5
Aman Khan        5
Kavya Mehta      5
Name: count, dtype: int64

In [183]:
# 1. Standardize missing-value markers such as N/A, unknown, blank strings and - wherever appropriate.


df.replace(["N/A", "Unknown","unknown", " ", "-"], 'nan', inplace=True)
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks,Performance_Level
0,S075,Rohit Joshi,Male,10th,Science,81.0,3.5,95.0,Sikar,YES,2025-01-15,good,A+
1,S002,Neha Patel,Male,10th,English,81.0,3.5,80.0,Jodhpur,NaN,2025-01-15,Not Provided,A
2,S092,Aarav Sharma,nan,12th,Computer Science,95.0,2.5,74.0,Jodhpur,no,2025-01-15,Absent,A
3,S021,Pooja Kumari,Female,11th,Computer Science,76.0,0.0,95.0,Sikar,Yes,2025-01-15,good,A+
4,S092,Vikas Yadav,Male,12th,Computer Science,81.0,0.0,72.0,jaipur,Yes,2025-01-15,Not Provided,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S011,Mohit Saini,Female,10th,Science,62.0,1.0,74.0,Delhi,NaN,2025-01-15,good,A
116,S022,Aarav Sharma,Female,10th,Maths,81.0,3.5,67.0,nan,Y,2025-01-15,good,B
117,S073,Karan Das,Male,10th,Maths,62.0,2.5,88.0,Jaipur,No,2025-01-15,Not Provided,A
118,S042,Vikas Yadav,Male,10th,Maths,95.0,3.5,74.0,nan,Yes,2025-01-15,Absent,A
119,S044,Priya Singh,Female,10th,English,88.0,3.5,95.0,Delhi,YES,2025-01-15,Good,A+

In [127]:
print(df.isnull().sum())

Student_ID              0
Student Name            0
Gender                  8
Class                   6
Subject                 8
Attendance_%           24
Study_Hours_Per_Day    10
Exam_Score              8
City                   10
Parent_Contacted       16
Exam_Date              21
Remarks                30
dtype: int64

In [128]:
df["Class"].unique()
df["Class"] = df["Class"].replace({
    "Ten": "10th",
    "Class 10":"10th",
    "XI":"11th",
    "Class 12":"12th",
    "11":"11th",
    "12":"12th",
    "10":"10th"

})
df["Class"].unique()

array([nan, '10th', '12th', '11th'], dtype=object)

In [129]:
# 3. Standardize Gender values into consistent categories.


df["Gender"] = df["Gender"].str.strip().str.lower()

df["Gender"] = df["Gender"].replace({
    "male": "Male",
    "m": "Male",
    "female": "Female",
    "f": "Female"
})

In [130]:
print(df["Gender"].unique())

['Male' 'unknown' 'Female' nan]

In [131]:
# 4. Standardize Subject names, such as Mathematics and math.
print(df["Subject"].unique())

['SCIENCE' 'English' 'Computer Science' 'Maths' 'Mathematics' 'Computer'
 'english' 'math' 'Science' nan]

In [132]:
df["Subject"] = df["Subject"].replace({
    "english":"English",
    "math":"Maths",
    "Mathematics":"Maths",
    "SCIENCE":"Science"
})
print(df["Subject"].unique())

['Science' 'English' 'Computer Science' 'Maths' 'Computer' nan]

In [133]:
print(df["Subject"].unique())

['Science' 'English' 'Computer Science' 'Maths' 'Computer' nan]

In [134]:
# 5. Standardize City names with consistent capitalization.
print(df["City"].unique())

[nan 'Jodhpur' 'Jodhpur ' ' jaipur ' 'Unknown' 'Delhi' 'sikar' 'Sikar'
 'Jaipur' 'SIKAR']

In [135]:
df["City"] = df["City"].replace({
    "jaipur":"Jaipur",
    "Jodhpur ":"Jodhpur",
    "SIKAR":"Sikar",
    "sikar":"Sikar"
})

In [136]:
print(df["City"].unique())

[nan 'Jodhpur' ' jaipur ' 'Unknown' 'Delhi' 'Sikar' 'Jaipur']

In [137]:
# 6. Convert Attendance_%, Study_Hours_Per_Day and Exam_Score into numeric data types.
col = ["Attendance_%", "Study_Hours_Per_Day","Exam_Score"]
for cols in col:
    df[cols] = pd.to_numeric(df[cols],errors="coerce")

In [138]:
# 7. Identify attendance values outside 0–100, negative study hours and exam scores outside 0–100.

df[df["Attendance_%"].lt(0)|df["Attendance_%"].gt(100)]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
1,S002,Neha Patel,Male,10th,English,105.0,3.5,80.0,Jodhpur,nan,not recorded,NaN
7,S026,Isha Agarwal,Female,10th,Computer,105.0,3.5,101.0,Unknown,Yes,not recorded,late submission
15,S062,Arjun Rao,NaN,10th,English,-5.0,6.0,74.0,Sikar,Y,2026-09-15,Absent
26,S007,Sneha Gupta,Female,11th,Maths,105.0,5.0,80.0,Unknown,YES,2026-09-15,Good
27,S054,Pooja Kumari,Female,12th,English,-5.0,-2.0,-10.0,Sikar,nan,2026/09/15,Needs improvement
41,S095,Rohit Joshi,unknown,12th,English,105.0,5.0,72.0,jaipur,No,15/09/2026,Absent
52,S065,Priya Singh,unknown,10th,Science,105.0,-2.0,95.0,Unknown,N,not recorded,Good
57,S016,Priya Singh,NaN,10th,Maths,105.0,-2.0,-10.0,Sikar,NaN,2026-09-15,Excellent
60,S056,Arjun Rao,Male,10th,Maths,105.0,NaN,72.0,Jodhpur,N,15/09/2026,NaN
63,S037,Aman Khan,Female,12th,Maths,105.0,4.0,101.0,Delhi,No,15/09/2026,Absent
65,S012,Rohit Joshi,unknown,12th,Maths,-5.0,-2.0,95.0,Jaipur,Yes,2026-13-40,NaN
66,S103,Isha Agarwal,NaN,10th,English,105.0,0.0,72.0,Sikar,N,not recorded,Needs improvement
69,S023,Neha Patel,Female,10th,English,105.0,3.5,74.0,Sikar,NaN,2026/09/15,nan
83,S005,Isha Agarwal,Male,10th,Maths,-5.0,3.5,80.0,Jodhpur,NaN,15/09/2026,Needs improvement
85,S034,Rahul Verma,Female,11th,Maths,105.0,6.0,74.0,Sikar,no,2026/09/15,Absent
89,S051,Neha Patel,Female,12th,Maths,-5.0,-2.0,95.0,NaN,nan,15/09/2026,good
97,S057,Rahul Verma,Male,11th,Computer Science,105.0,NaN,NaN,jaipur,Y,15/09/2026,late submission
105,S092,Rohit Joshi,Male,12th,Computer Science,105.0,1.0,95.0,Sikar,NaN,15/09/2026,Absent
106,S048,Neha Patel,Male,11th,Science,105.0,-2.0,101.0,NaN,No,15/09/2026,NaN
112,S025,Aman Khan,unknown,11th,Computer Science,-5.0,3.5,88.0,Delhi,N,15/09/2026,NaN
116,S022,Aarav Sharma,Female,NaN,Maths,-5.0,3.5,67.0,Unknown,Y,2026-09-15,good
122,S062,Arjun Rao,NaN,10th,English,-5.0,6.0,74.0,Sikar,Y,2026-09-15,Absent

In [139]:
df[df["Study_Hours_Per_Day"]<0]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
27,S054,Pooja Kumari,Female,12th,English,-5.0,-2.0,-10.0,Sikar,nan,2026/09/15,Needs improvement
34,S086,Rohit Joshi,Male,10th,Computer Science,NaN,-2.0,NaN,Jodhpur,Yes,not recorded,nan
38,S001,Aarav Sharma,unknown,12th,Maths,88.0,-2.0,NaN,Unknown,nan,NaN,NaN
52,S065,Priya Singh,unknown,10th,Science,105.0,-2.0,95.0,Unknown,N,not recorded,Good
53,S061,Karan Das,Female,10th,Science,62.0,-2.0,NaN,Sikar,no,2026-13-40,NaN
57,S016,Priya Singh,NaN,10th,Maths,105.0,-2.0,-10.0,Sikar,NaN,2026-09-15,Excellent
59,S033,Pooja Kumari,Female,10th,Science,78.0,-2.0,88.0,Sikar,Y,not recorded,Absent
65,S012,Rohit Joshi,unknown,12th,Maths,-5.0,-2.0,95.0,Jaipur,Yes,2026-13-40,NaN
78,S033,Sneha Gupta,unknown,10th,Computer,78.0,-2.0,101.0,Sikar,Y,2026-13-40,NaN
89,S051,Neha Patel,Female,12th,Maths,-5.0,-2.0,95.0,NaN,nan,15/09/2026,good
95,S041,Karan Das,unknown,10th,NaN,NaN,-2.0,95.0,Unknown,N,2026/09/15,NaN
96,S001,Aarav Sharma,Female,11th,NaN,62.0,-2.0,67.0,Sikar,NaN,2026-13-40,NaN
98,S082,Rahul Verma,Male,10th,NaN,78.0,-2.0,72.0,NaN,YES,15/09/2026,Good
106,S048,Neha Patel,Male,11th,Science,105.0,-2.0,101.0,NaN,No,15/09/2026,NaN
109,S081,Priya Singh,Female,10th,Science,NaN,-2.0,NaN,Unknown,No,2026-13-40,Excellent

In [140]:
df[df["Exam_Score"].lt(0)|df["Exam_Score"].gt(100)]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
7,S026,Isha Agarwal,Female,10th,Computer,105.0,3.5,101.0,Unknown,Yes,not recorded,late submission
9,S103,Aarav Sharma,Male,10th,Maths,95.0,2.5,101.0,Jodhpur,No,2026-09-15,NaN
18,S032,Rohit Joshi,Female,10th,Maths,76.0,3.5,101.0,Jodhpur,N,not recorded,NaN
27,S054,Pooja Kumari,Female,12th,English,-5.0,-2.0,-10.0,Sikar,nan,2026/09/15,Needs improvement
29,S060,Kavya Mehta,Female,10th,Science,90.0,2.0,101.0,Sikar,Yes,not recorded,NaN
30,S067,Rohit Joshi,Female,10th,Maths,NaN,NaN,-10.0,Jodhpur,nan,2026-13-40,Excellent
51,S046,Karan Das,NaN,12th,NaN,NaN,2.0,-10.0,NaN,Y,15/09/2026,late submission
56,S099,Anjali Jain,Female,12th,Science,78.0,NaN,101.0,jaipur,YES,not recorded,late submission
57,S016,Priya Singh,NaN,10th,Maths,105.0,-2.0,-10.0,Sikar,NaN,2026-09-15,Excellent
63,S037,Aman Khan,Female,12th,Maths,105.0,4.0,101.0,Delhi,No,15/09/2026,Absent
71,S070,Rahul Verma,Female,11th,Maths,NaN,NaN,-10.0,Delhi,Yes,NaN,late submission
75,S039,Anjali Jain,Male,10th,Maths,NaN,4.0,101.0,Jodhpur,Yes,2026-09-15,NaN
78,S033,Sneha Gupta,unknown,10th,Computer,78.0,-2.0,101.0,Sikar,Y,2026-13-40,NaN
86,S085,Aarav Sharma,Male,12th,Computer,78.0,NaN,101.0,Sikar,Y,NaN,Absent
90,S097,Karan Das,Female,11th,English,78.0,5.0,-10.0,Sikar,Y,NaN,NaN
106,S048,Neha Patel,Male,11th,Science,105.0,-2.0,101.0,NaN,No,15/09/2026,NaN
113,S098,Aman Khan,unknown,12th,Science,78.0,NaN,-10.0,Unknown,no,NaN,late submission

In [141]:
# 8. Handle invalid numerical values using a clearly stated rule.
# Handle invalid attendance
df.loc[
    (df["Attendance_%"] < 0) | (df["Attendance_%"] > 100),
    "Attendance_%"
] = np.nan

# Handle negative study hours
df.loc[
    df["Study_Hours_Per_Day"] < 0,
    "Study_Hours_Per_Day"
] = np.nan

# Handle invalid exam scores
df.loc[
    (df["Exam_Score"] < 0) | (df["Exam_Score"] > 100),
    "Exam_Score"
] = np.nan




print(df["Attendance_%"])

0      81.0
1       NaN
2      95.0
3      76.0
4       NaN
       ...
118    95.0
119    88.0
120    95.0
121     NaN
122     NaN
Name: Attendance_%, Length: 123, dtype: float64

In [142]:
# 9. Remove exact duplicate rows, but do not automatically remove every repeated Student_ID.
df.drop_duplicates(inplace=True)

print("Remaining duplicate rows:", df.duplicated().sum())

Remaining duplicate rows: 0

In [143]:
print(df["Exam_Date"].head(5))

0             NaN
1    not recorded
2      2026-13-40
3      15/09/2026
4    not recorded
Name: Exam_Date, dtype: object

In [144]:
# 10. Convert Exam_Date into a proper datetime data type and identify invalid dates.
df["Exam_Date"] = pd.to_datetime(df["Exam_Date"],format="%d-%m-%Y",errors="coerce")

In [145]:
print(df["Exam_Date"].head(5))

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Exam_Date, dtype: datetime64[ns]

In [146]:
# 11. Handle missing numerical and categorical values using suitable strategies.

num_cols = [
    "Attendance_%",
    "Study_Hours_Per_Day",
    "Exam_Score"
]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

print(df.isnull().sum())

Student_ID               0
Student Name             0
Gender                   7
Class                    6
Subject                  8
Attendance_%             0
Study_Hours_Per_Day      0
Exam_Score               0
City                    10
Parent_Contacted        15
Exam_Date              120
Remarks                 30
dtype: int64

In [147]:
cat_cols = [
    "Gender",
    "Class",
    "Subject",
    "City",
    "Parent_Contacted"
]

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])





df["Remarks"] = df["Remarks"].fillna("Not Provided")


print(df["Exam_Date"].isna().sum())

df["Exam_Date"] = df["Exam_Date"].fillna(pd.Timestamp("2025-01-15"))

print(df.isnull().sum())

120
Student_ID             0
Student Name           0
Gender                 0
Class                  0
Subject                0
Attendance_%           0
Study_Hours_Per_Day    0
Exam_Score             0
City                   0
Parent_Contacted       0
Exam_Date              0
Remarks                0
dtype: int64

In [148]:
# Part 4 — Pandas Analysis
# 1. Calculate the mean, median, minimum and maximum exam score.
print("Mean =",df["Exam_Score"].mean())
print("Median =",df["Exam_Score"].median())
print("Minimum =",df["Exam_Score"].min())
print("Maximum =",df["Exam_Score"].max())

Mean = 75.49166666666666
Median = 74.0
Minimum = 43.0
Maximum = 95.0

In [149]:
# 2. Find the average attendance percentage.
print("Average attendance percentage =",df["Attendance_%"].mean())

Average attendance percentage = 81.16666666666667

In [150]:
# 3. Display records of students whose exam score is greater than or equal to 70.
df[df["Exam_Score"]>=70]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,Male,10th,Science,81.0,3.5,95.0,Sikar,YES,2025-01-15,good
1,S002,Neha Patel,Male,10th,English,81.0,3.5,80.0,Jodhpur,nan,2025-01-15,Not Provided
2,S092,Aarav Sharma,unknown,12th,Computer Science,95.0,2.5,74.0,Jodhpur,no,2025-01-15,Absent
3,S021,Pooja Kumari,Female,11th,Computer Science,76.0,0.0,95.0,Sikar,Yes,2025-01-15,good
4,S092,Vikas Yadav,Male,12th,Computer Science,81.0,0.0,72.0,jaipur,Yes,2025-01-15,Not Provided
...,...,...,...,...,...,...,...,...,...,...,...,...
114,S046,Aman Khan,Female,12th,Maths,81.0,0.0,74.0,Jodhpur,nan,2025-01-15,nan
115,S011,Mohit Saini,Female,10th,Science,62.0,1.0,74.0,Delhi,nan,2025-01-15,good
117,S073,Karan Das,Male,10th,Maths,62.0,2.5,88.0,Jaipur,No,2025-01-15,Not Provided
118,S042,Vikas Yadav,Male,10th,Maths,95.0,3.5,74.0,Unknown,Yes,2025-01-15,Absent
119,S044,Priya Singh,Female,10th,English,88.0,3.5,95.0,Delhi,YES,2025-01-15,Good

In [151]:
# 4. Find the average exam score for each subject.
df.groupby("Subject")["Exam_Score"].mean()

Subject
Computer            68.200000
Computer Science    81.272727
English             77.833333
Maths               75.345455
Science             74.538462
Name: Exam_Score, dtype: float64

In [152]:
# 5. Find the average exam score for each class.
df.groupby("Class")["Exam_Score"].mean()

Class
10th    76.126984
11th    73.782609
12th    75.470588
Name: Exam_Score, dtype: float64

In [163]:
df.groupby("Subject")["Exam_Score"].sum()

Subject
Computer             682.0
Computer Science     894.0
English             1401.0
Maths               4144.0
Science             1938.0
Name: Exam_Score, dtype: float64

In [164]:
df.loc[df["Attendance_%"].idxmax()]

Student_ID                         S092
Student Name               Aarav Sharma
Gender                          unknown
Class                              12th
Subject                Computer Science
Attendance_%                       95.0
Study_Hours_Per_Day                 2.5
Exam_Score                         74.0
City                            Jodhpur
Parent_Contacted                     no
Exam_Date                    2025-01-15
Remarks                          Absent
Performance_Level                     A
Name: 2, dtype: object

In [165]:
print(df["Study_Hours_Per_Day"].mean())

3.095833333333333

In [153]:
# 6. Count records belonging to each subject and gender.
print(df["Subject"].value_counts())

Subject
Maths               55
Science             26
English             18
Computer Science    11
Computer            10
Name: count, dtype: int64

In [154]:
print(df["Gender"].value_counts())

Gender
Male       56
Female     45
unknown    19
Name: count, dtype: int64

In [155]:
# 7. Find the highest and lowest recorded exam scores.
print("Highest record=",df["Exam_Score"].max())
print("Lowest record=",df["Exam_Score"].min())

Highest record= 95.0
Lowest record= 43.0

In [156]:
# 8. Sort records by Exam_Score in descending order.
print(df["Exam_Score"].sort_values(ascending=False))

0      95.0
23     95.0
105    95.0
103    95.0
101    95.0
       ...
80     43.0
99     43.0
100    43.0
58     43.0
92     43.0
Name: Exam_Score, Length: 120, dtype: float64

In [ ]:
# 9. Create a new column named Performance_Level using a rule you define and document.
condition = [
    df["Exam_Score"] >= 90,
    df["Exam_Score"] >= 70,
    df["Exam_Score"] >= 60,
    df["Exam_Score"] >= 50

]

choice = [
    "A+",
    "A",
    "B",
    "C"
]

df["Performance_Level"] = np.select(condition,choice,default="Fail")
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks,Performance_Level
0,S075,Rohit Joshi,Male,10th,Science,81.0,3.5,95.0,Sikar,YES,2025-01-15,good,A+
1,S002,Neha Patel,Male,10th,English,81.0,3.5,80.0,Jodhpur,nan,2025-01-15,Not Provided,A
2,S092,Aarav Sharma,unknown,12th,Computer Science,95.0,2.5,74.0,Jodhpur,no,2025-01-15,Absent,A
3,S021,Pooja Kumari,Female,11th,Computer Science,76.0,0.0,95.0,Sikar,Yes,2025-01-15,good,A+
4,S092,Vikas Yadav,Male,12th,Computer Science,81.0,0.0,72.0,jaipur,Yes,2025-01-15,Not Provided,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S011,Mohit Saini,Female,10th,Science,62.0,1.0,74.0,Delhi,nan,2025-01-15,good,A
116,S022,Aarav Sharma,Female,10th,Maths,81.0,3.5,67.0,Unknown,Y,2025-01-15,good,B
117,S073,Karan Das,Male,10th,Maths,62.0,2.5,88.0,Jaipur,No,2025-01-15,Not Provided,A
118,S042,Vikas Yadav,Male,10th,Maths,95.0,3.5,74.0,Unknown,Yes,2025-01-15,Absent,A
119,S044,Priya Singh,Female,10th,English,88.0,3.5,95.0,Delhi,YES,2025-01-15,Good,A+

In [158]:
# 10. Calculate the correlation between attendance and exam score.
cor = df["Attendance_%"].corr(df["Exam_Score"])
print("Correlation between attendance and exam score:",cor)

Correlation between attendance and exam score: 0.12036006549198046

In [161]:
# Part 5 — Export and ML Connection
# 1. Export the cleaned DataFrame to cleaned_student_performance.csv without saving the index.
df.to_csv("cleaned_student_performance.csv",index=False)

In [162]:
# 2. Reload the exported CSV and verify its shape and data types.
df = pd.read_csv(r"C:\Users\Hp\OneDrive\Desktop\Advance python\cleaned_student_performance.csv")
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks,Performance_Level
0,S075,Rohit Joshi,Male,10th,Science,81.0,3.5,95.0,Sikar,YES,2025-01-15,good,A+
1,S002,Neha Patel,Male,10th,English,81.0,3.5,80.0,Jodhpur,NaN,2025-01-15,Not Provided,A
2,S092,Aarav Sharma,unknown,12th,Computer Science,95.0,2.5,74.0,Jodhpur,no,2025-01-15,Absent,A
3,S021,Pooja Kumari,Female,11th,Computer Science,76.0,0.0,95.0,Sikar,Yes,2025-01-15,good,A+
4,S092,Vikas Yadav,Male,12th,Computer Science,81.0,0.0,72.0,jaipur,Yes,2025-01-15,Not Provided,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,S011,Mohit Saini,Female,10th,Science,62.0,1.0,74.0,Delhi,NaN,2025-01-15,good,A
116,S022,Aarav Sharma,Female,10th,Maths,81.0,3.5,67.0,Unknown,Y,2025-01-15,good,B
117,S073,Karan Das,Male,10th,Maths,62.0,2.5,88.0,Jaipur,No,2025-01-15,Not Provided,A
118,S042,Vikas Yadav,Male,10th,Maths,95.0,3.5,74.0,Unknown,Yes,2025-01-15,Absent,A
119,S044,Priya Singh,Female,10th,English,88.0,3.5,95.0,Delhi,YES,2025-01-15,Good,A+