In [2]:
# Part 1 — Data Inspection
# 1. Import Pandas and NumPy libraries.
# 2. Load the CSV file into a DataFrame named df.

import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\Hp\OneDrive\Desktop\Advance python\student_performance_dataset.csv")
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,unknown,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,unknown,not recorded,NaN
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,Unknown,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [3]:
# 3. Display the first 10 and last 5 rows.
print(df.head(10))
print(df.tail(5))

  Student_ID  Student Name   Gender Class           Subject Attendance_%  \
0       S075   Rohit Joshi     MALE   NaN           SCIENCE           81
1       S002    Neha Patel       m   10th           English          105
2       S092  Aarav Sharma  Unknown    12  Computer Science           95
3       S021  Pooja Kumari       f     XI  Computer Science           76
4       S092   Vikas Yadav     Male  12th  Computer Science          NaN
5       S002  Pooja Kumari       m   10th             Maths           62
6       S062   Anjali Jain     MALE    12       Mathematics          NaN
7       S026  Isha Agarwal       f    Ten          Computer          105
8       S088     Arjun Rao   Female   Ten           english          NaN
9       S103  Aarav Sharma       m   10th              math           95

  Study_Hours_Per_Day Exam_Score      City Parent_Contacted     Exam_Date  \
0             unknown         95       NaN              YES           NaN
1                 3.5         80   Jodhpur          unknown  not recorded
2                2.5         74   Jodhpur                no    2026-13-40
3                   0         95       NaN              Yes    15/09/2026
4                   0         72   jaipur               NaN  not recorded
5                 3.5         80   jaipur                 N    2026-13-40
6               three         72  Jodhpur                no    2026-13-40
7                 3.5        101   Unknown              Yes  not recorded
8                   6         88   Unknown              NaN    2026/09/15
9                2.5         101  Jodhpur                No    2026-09-15

           Remarks
0            good
1              NaN
2           Absent
3            good
4              NaN
5                -
6        Excellent
7  late submission
8           Absent
9              NaN
    Student_ID  Student Name   Gender Class           Subject Attendance_%  \
118       S042   Vikas Yadav      NaN   NaN             Maths           95
119       S044   Priya Singh        F  10th           English           88
120       S092  Aarav Sharma  Unknown    12  Computer Science           95
121       S088     Arjun Rao   Female   Ten           english          NaN
122       S062     Arjun Rao      NaN  10th           english           -5

    Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
118                 NaN        74    Unknown              Yes  2026/09/15
119               three         95     Delhi              YES  2026/09/15
120                2.5         74   Jodhpur                no  2026-13-40
121                   6         88   Unknown              NaN  2026/09/15
122                   6        74      sikar                Y  2026-09-15

    Remarks
118  Absent
119    Good
120  Absent
121  Absent
122  Absent

In [4]:
# 4. Find the total number of rows and columns.
print(df.shape)

(123, 12)

In [5]:
# 5. Display all column names and their data types.
print(df.dtypes)

Student_ID             object
Student Name           object
Gender                 object
Class                  object
Subject                object
Attendance_%           object
Study_Hours_Per_Day    object
Exam_Score             object
City                   object
Parent_Contacted       object
Exam_Date              object
Remarks                object
dtype: object

In [6]:
# 6. Check the DataFrame information using info() and summary statistics using describe().
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student_ID           123 non-null    object
 1   Student Name         123 non-null    object
 2   Gender               115 non-null    object
 3   Class                117 non-null    object
 4   Subject              115 non-null    object
 5   Attendance_%         99 non-null     object
 6   Study_Hours_Per_Day  113 non-null    object
 7   Exam_Score           115 non-null    object
 8   City                 113 non-null    object
 9   Parent_Contacted     107 non-null    object
 10  Exam_Date            102 non-null    object
 11  Remarks              93 non-null     object
dtypes: object(12)
memory usage: 11.7+ KB
None

In [7]:
print(df.describe(include ="all"))

       Student_ID  Student Name   Gender Class Subject Attendance_%  \
count         123           123      115   117     115           99
unique         74            15        9     9       9           10
top          S092  Aarav Sharma  Unknown  10th   Maths          105
freq            6            11       20    19      21           14

       Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
count                  113        115       113              107         102
unique                  11         11         9                7           5
top                     -2         88  Jodhpur               Yes  2026-13-40
freq                    15         16        21               22          27

       Remarks
count       93
unique       7
top      good
freq        19

In [8]:
# Part 2 — Data Quality Check
# 1. Count missing values in each column.
print(df.isnull().sum())

Student_ID              0
Student Name            0
Gender                  8
Class                   6
Subject                 8
Attendance_%           24
Study_Hours_Per_Day    10
Exam_Score              8
City                   10
Parent_Contacted       16
Exam_Date              21
Remarks                30
dtype: int64

In [9]:
# 2. Calculate the percentage of missing values in each column.
print(df.isnull().mean()*100)

Student_ID              0.000000
Student Name            0.000000
Gender                  6.504065
Class                   4.878049
Subject                 6.504065
Attendance_%           19.512195
Study_Hours_Per_Day     8.130081
Exam_Score              6.504065
City                    8.130081
Parent_Contacted       13.008130
Exam_Date              17.073171
Remarks                24.390244
dtype: float64

In [10]:
# 3. Count the exact duplicate rows.
print(df.duplicated().sum())

3

In [11]:
# 4. Display all duplicate rows without deleting them.
print(df[df.duplicated(keep=False)])

    Student_ID  Student Name   Gender Class           Subject Attendance_%  \
2         S092  Aarav Sharma  Unknown    12  Computer Science           95
8         S088     Arjun Rao   Female   Ten           english          NaN
15        S062     Arjun Rao      NaN  10th           english           -5
120       S092  Aarav Sharma  Unknown    12  Computer Science           95
121       S088     Arjun Rao   Female   Ten           english          NaN
122       S062     Arjun Rao      NaN  10th           english           -5

    Study_Hours_Per_Day Exam_Score      City Parent_Contacted   Exam_Date  \
2                  2.5         74   Jodhpur                no  2026-13-40
8                     6         88   Unknown              NaN  2026/09/15
15                    6        74      sikar                Y  2026-09-15
120                2.5         74   Jodhpur                no  2026-13-40
121                   6         88   Unknown              NaN  2026/09/15
122                   6        74      sikar                Y  2026-09-15

    Remarks
2    Absent
8    Absent
15   Absent
120  Absent
121  Absent
122  Absent

In [12]:
# 5. Find the number of unique values in every column.
print(df.nunique())

Student_ID             74
Student Name           15
Gender                  9
Class                   9
Subject                 9
Attendance_%           10
Study_Hours_Per_Day    11
Exam_Score             11
City                    9
Parent_Contacted        7
Exam_Date               5
Remarks                 7
dtype: int64

In [13]:
# 6. Display unique values of Gender, Class, Subject and City.
print(df["Gender"].unique())
print(df["Class"].unique())
print(df["Subject"].unique())
print(df["City"].unique())

['MALE' ' m ' 'Unknown' ' f ' 'Male' 'Female' 'female' nan 'F' 'M']
[nan '10th' '12' 'XI' '12th' 'Ten' 'Class 10' '11' 'Class 12' '10']
['SCIENCE' 'English' 'Computer Science' 'Maths' 'Mathematics' 'Computer'
 'english' 'math' 'Science' nan]
[nan 'Jodhpur' 'Jodhpur ' ' jaipur ' 'Unknown' 'Delhi' 'sikar' 'Sikar'
 'Jaipur' 'SIKAR']

In [14]:
# 7. Identify columns containing inconsistent text values or invalid data.
for col in ["Gender", "Class", "Subject", "City","Student Name"]:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Gender:
Gender
Unknown    20
 m         17
Female     14
MALE       13
M          13
F          12
 f         10
female     10
NaN         8
Male        6
Name: count, dtype: int64

Class:
Class
10th        19
12          15
10          15
11          14
Class 10    13
Ten         12
12th        11
XI           9
Class 12     9
NaN          6
Name: count, dtype: int64

Subject:
Subject
Maths               21
math                14
SCIENCE             13
english             13
Science             13
Computer Science    12
Mathematics         12
Computer            10
NaN                  8
English              7
Name: count, dtype: int64

City:
City
Jodhpur     21
Unknown     19
SIKAR       17
Delhi       14
sikar       11
NaN         10
 jaipur     10
Sikar        9
Jaipur       9
Jodhpur      3
Name: count, dtype: int64

Student Name:
Student Name
Aarav Sharma    11
Karan Das       11
Rohit Joshi     10
Neha Patel      10
Isha Agarwal    10
Arjun Rao       10
Vikas Yadav      9
Mohit Saini      9
Rahul Verma      8
Pooja Kumari     7
Anjali Jain      7
Priya Singh      6
Sneha Gupta      5
Aman Khan        5
Kavya Mehta      5
Name: count, dtype: int64

In [15]:
# 1. Standardize missing-value markers such as N/A, unknown, blank strings and - wherever appropriate.


df.replace(["N/A", "unknown", "", "-"], 'nan', inplace=True)
df

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
0,S075,Rohit Joshi,MALE,NaN,SCIENCE,81,nan,95,NaN,YES,NaN,good
1,S002,Neha Patel,m,10th,English,105,3.5,80,Jodhpur,nan,not recorded,NaN
2,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
3,S021,Pooja Kumari,f,XI,Computer Science,76,0,95,NaN,Yes,15/09/2026,good
4,S092,Vikas Yadav,Male,12th,Computer Science,NaN,0,72,jaipur,NaN,not recorded,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
118,S042,Vikas Yadav,NaN,NaN,Maths,95,NaN,74,Unknown,Yes,2026/09/15,Absent
119,S044,Priya Singh,F,10th,English,88,three,95,Delhi,YES,2026/09/15,Good
120,S092,Aarav Sharma,Unknown,12,Computer Science,95,2.5,74,Jodhpur,no,2026-13-40,Absent
121,S088,Arjun Rao,Female,Ten,english,NaN,6,88,Unknown,NaN,2026/09/15,Absent
122,S062,Arjun Rao,NaN,10th,english,-5,6,74,sikar,Y,2026-09-15,Absent

In [16]:
print(df.isnull().sum())

Student_ID              0
Student Name            0
Gender                  8
Class                   6
Subject                 8
Attendance_%           24
Study_Hours_Per_Day    10
Exam_Score              8
City                   10
Parent_Contacted       16
Exam_Date              21
Remarks                30
dtype: int64

In [17]:
# 3. Standardize Gender values into consistent categories.
df["Gender"].unique()

df["Gender"] = df["Gender"].replace({
    "MALE":"Male",
    "m":"Male",
    "female":"Female",
    "f":"Female"
})
print(df["Gender"])

0         Male
1           m
2      Unknown
3           f
4         Male
        ...
118        NaN
119          F
120    Unknown
121     Female
122        NaN
Name: Gender, Length: 123, dtype: object

In [18]:
print(df["Gender"].unique())

['Male' ' m ' 'Unknown' ' f ' 'Female' nan 'F' 'M']

In [19]:
# 4. Standardize Subject names, such as Mathematics and math.
print(df["Subject"].unique())

['SCIENCE' 'English' 'Computer Science' 'Maths' 'Mathematics' 'Computer'
 'english' 'math' 'Science' nan]

In [30]:
df["Subject"] = df["Subject"].replace({
    "english":"English",
    "math":"Maths",
    "Mathematics":"Maths",
    "SCIENCE":"Science"
})
print(df["Subject"])

0               Science
1               English
2      Computer Science
3      Computer Science
4      Computer Science
             ...
118               Maths
119             English
120    Computer Science
121             English
122             English
Name: Subject, Length: 123, dtype: object

In [31]:
print(df["Subject"].unique())

['Science' 'English' 'Computer Science' 'Maths' 'Computer' nan]

In [32]:
# 5. Standardize City names with consistent capitalization.
print(df["City"].unique())

[nan 'Jodhpur' 'Jodhpur ' ' jaipur ' 'Unknown' 'Delhi' 'sikar' 'Sikar'
 'Jaipur' 'SIKAR']

In [33]:
df["City"] = df["City"].replace({
    "jaipur":"Jaipur",
    "Jodhpur ":"Jodhpur",
    "SIKAR":"Sikar",
    "sikar":"Sikar"
})

In [34]:
print(df["City"].unique())

[nan 'Jodhpur' ' jaipur ' 'Unknown' 'Delhi' 'Sikar' 'Jaipur']

In [39]:
# 6. Convert Attendance_%, Study_Hours_Per_Day and Exam_Score into numeric data types.
col = ["Attendance_%", "Study_Hours_Per_Day","Exam_Score"]
for cols in col:
    df[cols] = pd.to_numeric(df[cols],errors="coerce")

In [ ]:

df[df["Attendance_%"].lt(0)|df["Attendance_%"].gt(100)]

,Student_ID,Student Name,Gender,Class,Subject,Attendance_%,Study_Hours_Per_Day,Exam_Score,City,Parent_Contacted,Exam_Date,Remarks
1,S002,Neha Patel,m,10th,English,105.0,3.5,80.0,Jodhpur,nan,not recorded,NaN
7,S026,Isha Agarwal,f,Ten,Computer,105.0,3.5,101.0,Unknown,Yes,not recorded,late submission
15,S062,Arjun Rao,NaN,10th,English,-5.0,6.0,74.0,Sikar,Y,2026-09-15,Absent
26,S007,Sneha Gupta,Female,XI,Maths,105.0,5.0,80.0,Unknown,YES,2026-09-15,Good
27,S054,Pooja Kumari,Female,12,English,-5.0,-2.0,-10.0,Sikar,nan,2026/09/15,Needs improvement
41,S095,Rohit Joshi,Unknown,12th,English,105.0,5.0,72.0,jaipur,No,15/09/2026,Absent
52,S065,Priya Singh,Unknown,Class 10,Science,105.0,-2.0,95.0,Unknown,N,not recorded,Good
57,S016,Priya Singh,NaN,10,Maths,105.0,-2.0,-10.0,Sikar,NaN,2026-09-15,Excellent
60,S056,Arjun Rao,M,Class 10,Maths,105.0,NaN,72.0,Jodhpur,N,15/09/2026,NaN
63,S037,Aman Khan,F,12,Maths,105.0,4.0,101.0,Delhi,No,15/09/2026,Absent
65,S012,Rohit Joshi,Unknown,12th,Maths,-5.0,-2.0,95.0,Jaipur,Yes,2026-13-40,NaN
66,S103,Isha Agarwal,NaN,10,English,105.0,0.0,72.0,Sikar,N,not recorded,Needs improvement
69,S023,Neha Patel,F,Class 10,English,105.0,3.5,74.0,Sikar,NaN,2026/09/15,nan
83,S005,Isha Agarwal,Male,10th,Maths,-5.0,3.5,80.0,Jodhpur,NaN,15/09/2026,Needs improvement
85,S034,Rahul Verma,Female,11,Maths,105.0,6.0,74.0,Sikar,no,2026/09/15,Absent
89,S051,Neha Patel,Female,Class 12,Maths,-5.0,-2.0,95.0,NaN,nan,15/09/2026,good
97,S057,Rahul Verma,m,11,Computer Science,105.0,NaN,NaN,jaipur,Y,15/09/2026,late submission
105,S092,Rohit Joshi,m,12,Computer Science,105.0,1.0,95.0,Sikar,NaN,15/09/2026,Absent
106,S048,Neha Patel,m,XI,Science,105.0,-2.0,101.0,NaN,No,15/09/2026,NaN
112,S025,Aman Khan,Unknown,XI,Computer Science,-5.0,3.5,88.0,Delhi,N,15/09/2026,NaN
116,S022,Aarav Sharma,f,NaN,Maths,-5.0,3.5,67.0,Unknown,Y,2026-09-15,good
122,S062,Arjun Rao,NaN,10th,English,-5.0,6.0,74.0,Sikar,Y,2026-09-15,Absent

In [ ]:
df[df[""]]

In [ ]:
# 8. Handle invalid numerical values using a clearly stated rule.

In [ ]:
# 9. Remove exact duplicate rows, but do not automatically remove every repeated Student_ID.

In [ ]:
# 10. Convert Exam_Date into a proper datetime data type and identify invalid dates.